import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter'
import ThemeProvider from '@mui/material/styles/ThemeProvider'
import type { Metadata } from 'next'
import { 
 Nunito  
 } from 'next/font/google'
import { WmNavbar } from '@/common/components/WmNavbar'
import theme from '@/common/theme'
import WmDrawer from '@/common/components/WmDrawer'
import { CssBaseline } from '@mui/material'
import WmToast from '@/common/components/WmToast'

const mainFont = Poppins({
  subsets: ['latin-ext'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'WiseMap',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang='en'>
      <AppRouterCacheProvider>
        <CssBaseline />
        <body className={mainFont.className}>
          <ThemeProvider theme={theme}>
            <WmNavbar />
            <WmDrawer />
            {children}
            <WmToast />
          </ThemeProvider>
        </body>
      </AppRouterCacheProvider>
    </html>
  )
}
